# """ Elabore pseudocódigo para el caso en que se desean escribir los números 
# del 1 al 100 """

class Ejemplo11:
    def __init__(self):
        pass
    
    def pseudo (self):
        Numero= 1
        while Numero <= 100 :
            print("El numero ha sido ingresado con exito: "+str(Numero))
            Numero= Numero+1
        print ("Ejecucion Terminada")
        
      
        
        
        
            
eje11= Ejemplo11()
eje11.pseudo()